language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer install
script:
  - phpunit
